trigger:
- none

pool:
  name: Default

variables:
#   # Update these with your actual Azure Service Connection and Backend details
#   azureServiceConnection: 'your-service-connection-name'
#   resourceGroupName: 'your-backend-rg'
#   storageAccountName: 'your-backend-storage-account'
#   containerName: 'tfstate'
#   tfstateKey: 'dev.terraform.tfstate'
  workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'

stages:
- stage: Lint
  displayName: 'Linting Stage'
  jobs:
  - job: Terraform_Lint
    displayName: 'Terraform Validate and Lint'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - script: |
        cd $(workingDirectory)
        terraform init -backend=false
        terraform validate
      displayName: 'Terraform Init and Validate'

- stage: Plan
  displayName: 'Terraform Plan Stage'
  dependsOn: Lint
  jobs:
  - job: Terraform_Plan
    displayName: 'Terraform Plan'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(workingDirectory)'
        backendServiceArm: 'rahul_svc'
        backendAzureRmResourceGroupName: 'rg-terraform-state'
        backendAzureRmStorageAccountName: 'sttfstatedev08'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'rahulp'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(workingDirectory)'
        environmentServiceNameAzureRM: 'rahul_svc'

- stage: Apply
  displayName: 'Terraform Apply Stage'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: Terraform_Apply
    displayName: 'Terraform Apply'
    environment: 'production' # Use Azure DevOps environment for manual approval
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm: 'rahul_svc'
              backendAzureRmResourceGroupName: 'rg-terraform-state'
              backendAzureRmStorageAccountName: 'sttfstatedev08'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'rahulp'
          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: 'rahul_svc'
